baseURL: "https://blog.pythoner.work/"
title: "hanson.blog(); | A lifelong programmer."
copyright: "Copyright &copy; 2009–2025 Hanson Hu"
theme: "papermod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true
  # minifyOutput: true

pagination:
  disableAliases: false
  pagerSize: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai

services:
  googleAnalytics:
    id: G-V0C7EH4L0P
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
