languageName: "EN"
weight: 1
taxonomies:
  category: categories
  tag: tags
  series: series
menu:
  main:
    - name: Categories
      url: categories/
      weight: 10
    - name: Tags
      url: tags/
      weight: 20
    - name: Search
      url: search/
      weight: 30
    - name: About
      url: about/
      weight: 40

params:
  description: "A lifelong programmer."
  author: "Hanson Hu"
