env: production

defaultTheme: auto
ShowShareButtons: false
ShowReadingTime: true
displayFullLangName: true
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowRssButtonInSectionTermList: true
ShowAllPagesInArchive: true
ShowPageNums: true
ShowToc: true
# comments: false
images: ["images/markdown.png"]

homeInfoParams:
  Title: "Java for food, Python for fun"
  Content: >
    👋 Welcome to my weblog.

    - Feel free to show your support by giving me a star 🌟 on GitHub or subscribe to it with your favorite RSS reader.

socialIcons:
  - name: github
    title: GitHub
    url: "https://github.com/hanson2010/hanson2010.github.io"
  - name: rss
    title: RSS
    url: "index.xml"

analytics:
  # google:
    # SiteVerificationTag: "XYZabc"

assets:
  disableHLJS: true
#     favicon: "<link / abs url>"
#     favicon16x16: "<link / abs url>"
#     favicon32x32: "<link / abs url>"
#     apple_touch_icon: "<link / abs url>"
#     safari_pinned_tab: "<link / abs url>"

# cover:
#     hidden: true # hide everywhere but not in structured data
#     hiddenInList: true # hide on list pages and home
#     hiddenInSingle: true # hide on single page

# fuseOpts:
#     isCaseSensitive: false
#     shouldSort: true
#     location: 0
#     distance: 1000
#     threshold: 0.4
#     minMatchCharLength: 0
#     keys: ["title", "permalink", "summary", "content"]
