baseurl = "https://blog.pythoner.work/"
title = "hanson.blog();"
copyright = "Copyright &copy; 2009–2022 Hanson Hu"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "myShortName"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Hanson Hu"
    github = "hanson2010"
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    twitter = "hanson2010"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname
    #devto = "username"

[params]
    tagline = "A lifelong programmer."
    description = "Knowledge, fun, and random thoughts."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    favicon = "/favicon.ico"
    utterancesRepo = "hanson2010/hanson2010.github.io"
    utterancesIssueTerm = "pathname"
    #homepageLength = 10
    #commentAutoload = true  #This mean reader don't need click, disqus comment autoload
    #mathjax = true #Enable display of mathematics using mathjax (LaTeX syntax)
    #katex = true #Enable display of mathematics using katex (Faster LaTeX rendering)
    #google_fonts = ["Staatliches"] # Adds additional google fonts
    #disableDarkModeCSS = false # disables css style for users using dark-mode

[[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/posts"
    weight = 1
[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 2
[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3
[[menu.main]]
    identifier = "rss"
    name = "RSS Feed"
    url = "/index.xml"
    weight = 4

[params.gitalk]
  owner = "hanson2010"
  repo = "hanson2010.github.io"
  client_id = "a342cb50d0eb7812a593"
  client_secret = "d5c4686542955356a733efc16815edb0cf217885"
