baseurl = "https://blog.pythoner.work/"
title = "hanson.blog();"
copyright = "Copyright &copy; 2009–2025 Hanson Hu"
canonifyurls = true
theme = "kiera"

[pagination]
    pagersize = 3

summaryLength = 20
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "myShortName"

[params.author]
    name = "Hanson Hu"
    github = "hanson2010"
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    twitter = "hanson2010"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname
    #devto = "username"

[params]
    tagline = "A lifelong programmer."
    description = "Knowledge, fun, and random thoughts."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = ["css/custom.css"]
    favicon = "/favicon.ico"
    utterancesRepo = "hanson2010/hanson2010.github.io"
    utterancesIssueTerm = "pathname"
    #homepageLength = 10
    #commentAutoload = true  #This mean reader don't need click, disqus comment autoload
    #mathjax = true #Enable display of mathematics using mathjax (LaTeX syntax)
    #katex = true #Enable display of mathematics using katex (Faster LaTeX rendering)
    #google_fonts = ["Staatliches"] # Adds additional google fonts
    #disableDarkModeCSS = false # disables css style for users using dark-mode

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/posts"
    weight = 1
[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 2
[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3
[[menu.main]]
    identifier = "rss"
    name = "RSS Feed"
    url = "/index.xml"
    weight = 4
